services:
  scriptlauncher:
    build:
      context: .  # Contexte de construction
      dockerfile: Dockerfile  # Spécifie le Dockerfile à utiliser
    volumes:
      - .:/app  # Monte le répertoire courant dans /app à l'intérieur du conteneur
    ports:
      - "8080:8080"