services:
  scriptlauncher:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8080:8080"
  
  fastapi-server:
    build:
      context: ./fastapi-app
    ports:
      - "8080:8080"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

    environment:
      - KUBECONFIG=./Dockerfile
