version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"  # Vous devez accepter l'EULA de Minecraft
      VERSION: "1.20"  # ou "1.20" pour une version spécifique
    volumes:
      - minecraft_data:/data  # Volume pour la persistance des données

volumes:
  minecraft_data:

