version: '3.8'

services:
  web:
    build: ./web  # Répertoire contenant votre Dockerfile pour l'app web
    ports:
      - "3000:3000"
    depends_on:
      - minecraft

  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - minecraft_data:/data

volumes:
  minecraft_data:
