services:
  ubuntu:
    image: ubuntu:latest
    volumes:
      - .:/app
    command: tail -f /dev/null  # Keeps the container running

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - ubuntu
