apiVersion: apps/v1
kind: Deployment
metadata:
  name: demominecraft
  labels:
    app: demominecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demominecraft
  template:
    metadata:
      labels:
        app: demominecraft
    spec:
      containers:
      - name: demominecraft
        image: itzg/minecraft-server 
        ports:
        - containerPort: 25565  
        env:
          - name: EULA
            value: "TRUE"  
