apiVersion: v1
kind: Service
metadata:
  name: demominecraft 
  labels:
    app: demominecraft 
spec:
  ports:
    - port: 25565        
      protocol: TCP      
      targetPort: 25565  
  selector:
    app: demominecraft  
  type: ClusterIP      
