apiVersion: v1
kind: Service
metadata:
  name: demominecraft  # Name of the service
  labels:
    app: demominecraft  # Update label to match the deployment
spec:
  ports:
    - port: 25565        # Port that the service will expose
      protocol: TCP      # Protocol to use (TCP for Minecraft)
      targetPort: 25565  # Port on the pod to forward traffic to
  selector:
    app: demominecraft  # Selector to match the pods created by the deployment
  type: ClusterIP       # ClusterIP is the default service type